# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x03tts\"I\n\x0fGenerateRequest\x12\x10\n\x08pdf_path\x18\x01 \x01(\t\x12\x12\n\nstart_page\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_page\x18\x03 \x01(\x05\";\n\rGenerateReply\x12\x19\n\x11output_audio_path\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2I\n\x0cTextToSpeech\x12\x39\n\rGenerateAudio\x12\x14.tts.GenerateRequest\x1a\x12.tts.GenerateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=18
  _globals['_GENERATEREQUEST']._serialized_end=91
  _globals['_GENERATEREPLY']._serialized_start=93
  _globals['_GENERATEREPLY']._serialized_end=152
  _globals['_TEXTTOSPEECH']._serialized_start=154
  _globals['_TEXTTOSPEECH']._serialized_end=227
# @@protoc_insertion_point(module_scope)
